project:
  type: website
  pre-render:
  - parameterRateOfChange/generate_batch_qmds.R
  - SEACARParameterCompare/generate_batch_qmds.R
  - SEACARProgramCompare/generate_batch_qmds.R
  render:
  - prepDashboardExport.qmd

  - index.qmd
  - usage_examples/map_program_parameter_subset.qmd
  - usage_examples/plot_slopes.qmd
  - SEACAROverallCompare.qmd
  - SEACARDepthComparison.qmd
  - randomSampleDrilldown.qmd
  - rateOfChangeChange.qmd

  - parameterRateOfChange/batched_reports/*.qmd
  - parameterRateOfChange/listing.qmd
  
  - SEACARParameterCompare/batched_reports/*.qmd
  - SEACARParameterCompare/listing.qmd
  
  - SEACARProgramCompare/batched_reports/*.qmd
  - SEACARProgramCompare/listing.qmd
  
website:
  title: FCRWQDC SEACAR Analysis
  navbar:
    left:
    - href: index.qmd
      text: Home
    - parameterRateOfChange/listing.qmd
    - prepDashboardExport.qmd
    - text: "SEACAR Comparisons"
      menu:
      - SEACAROverallCompare.qmd
      - SEACARParameterCompare/listing.qmd
      - SEACARProgramCompare/listing.qmd
      - SEACARDepthComparison.qmd
      - randomSampleDrilldown.qmd
      - rateOfChangeChange.qmd
    - text: "Data Usage Examples"
      menu:
        - href: usage_examples/map_program_parameter_subset.qmd
          text: Map Program Parameter Subset
        - href: usage_examples/plot_slopes.qmd
          text: Map of Slope Values

    - href: https://github.com/USF-IMARS/FCRWQDC-SEACAR-analysis
      text: Source Code on GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    message: false
    warning: false

