project:
  type: website
  pre-render:
  - parameterRateOfChange/generate_batch_qmds.R
  - SEACARParameterCompare/generate_batch_qmds.R
  - SEACARProgramCompare/generate_batch_qmds.R
  render:
  - index.qmd
  - parameterRateOfChange/batched_reports/*.qmd
  - parameterRateOfChange/listing.qmd
  - SEACARParameterCompare/batched_reports/*.qmd
  - SEACARParameterCompare/listing.qmd
  - SEACARProgramCompare/batched_reports/*.qmd
  - SEACARProgramCompare/listing.qmd
website:
  title: FCRWQDC SEACAR Analysis
  navbar:
    left:
    - href: index.qmd
      text: Home
    - parameterRateOfChange/listing.qmd
    - text: "SEACAR Comparisons"
      menu:
      - SEACARParameterCompare/listing.qmd
      - SEACARProgramCompare/listing.qmd
    - href: https://github.com/USF-IMARS/FCRWQDC-SEACAR-analysis
      text: Source Code on GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    message: false
    warning: false

